version: "3.7"
services:
  app:
    build:
      context: ./.docker/php/
      dockerfile: Dockerfile
    image: botify
    container_name: botify-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/.docker/
    networks:
      - botify
  db:
    image: mysql:5.7
    container_name: botify-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - /var/www/.docker/
    networks:
      - botify

  nginx:
    image: nginx:1.17-alpine
    container_name: botify-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
      - /var/www/.docker/
    networks:
      - botify

networks:
  botify:
    driver: bridge